### ISSUE TITLE
アクセス権限の無いディレクトリがCLIの実行ディレクトリ配下にあるとエラーになる

### ISSUE THREAD

**Issue by haljik** [dddjava/Jig#144]
cliをmacのルートディレクトリなどで実行すると簡単に起こせる。

```
2018-08-26 12:46:01.071 ERROR 7752 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800) [spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781) [spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) [spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.dddjava.jig.cli.CommandLineApplication.main(CommandLineApplication.java:28) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [jig-cli.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [jig-cli.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [jig-cli.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [jig-cli.jar:na]
Caused by: java.io.UncheckedIOException: java.nio.file.AccessDeniedException: ./usr/sbin/authserver
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88) ~[na:1.8.0_181]
        at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104) ~[na:1.8.0_181]
        at java.util.Iterator.forEachRemaining(Iterator.java:115) ~[na:1.8.0_181]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_181]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_181]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_181]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545) ~[na:1.8.0_181]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[na:1.8.0_181]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438) ~[na:1.8.0_181]
        at org.dddjava.jig.infrastructure.DefaultLayout.extractClassPath(DefaultLayout.java:41) ~[jig-core-2018.8.4-SNAPSHOT.jar!/:na]
        at org.dddjava.jig.infrastructure.LocalProject.getByteCodeSources(LocalProject.java:39) ~[jig-core-2018.8.4-SNAPSHOT.jar!/:na]
        at org.dddjava.jig.application.service.ImplementationService.readProjectData(ImplementationService.java:38) ~[jig-core-2018.8.4-SNAPSHOT.jar!/:na]
        at org.dddjava.jig.cli.CommandLineApplication.run(CommandLineApplication.java:50) [classes!/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:797) [spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        ... 13 common frames omitted
Caused by: java.nio.file.AccessDeniedException: ./usr/sbin/authserver
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[na:1.8.0_181]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_181]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_181]
        at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:407) ~[na:1.8.0_181]
        at java.nio.file.Files.newDirectoryStream(Files.java:457) ~[na:1.8.0_181]
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300) ~[na:1.8.0_181]
        at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372) ~[na:1.8.0_181]
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:84) ~[na:1.8.0_181]
        ... 26 common frames omitted
```

**Comment by irof** [comment]
読み取り不可ファイルなどに当たった場合、エラー終了じゃなく警告ログあたりにしましょうか。
