### ISSUE TITLE
graphviz非インストール環境でダイアグラムが出力できない

### ISSUE THREAD

**Issue by irof** [dddjava/Jig#205]
GraphvizV8Engineを使って失敗している。

```
2018-11-14 13:57:57.343  INFO 20360 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-11-14 13:57:57.345 ERROR 20360 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:816) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
    at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
    at org.dddjava.jig.cli.CommandLineApplication.main(CommandLineApplication.java:28) [classes!/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [jig-cli.jar:na]
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [jig-cli.jar:na]
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [jig-cli.jar:na]
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [jig-cli.jar:na]
Caused by: guru.nidi.graphviz.engine.GraphvizException: TypeError: Module.print is not a function
    at guru.nidi.graphviz.engine.ResultHandler.waitFor(ResultHandler.java:42) ~[graphviz-java-0.7.0.jar!/:na]
    at guru.nidi.graphviz.engine.GraphvizV8Engine$Env.execute(GraphvizV8Engine.java:91) ~[graphviz-java-0.7.0.jar!/:na]
    at guru.nidi.graphviz.engine.GraphvizV8Engine.jsExecute(GraphvizV8Engine.java:67) ~[graphviz-java-0.7.0.jar!/:na]
    at guru.nidi.graphviz.engine.AbstractJsGraphvizEngine.execute(AbstractJsGraphvizEngine.java:28) ~[graphviz-java-0.7.0.jar!/:na]
    at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:186) ~[graphviz-java-0.7.0.jar!/:na]
    at guru.nidi.graphviz.engine.Renderer.toString(Renderer.java:46) ~[graphviz-java-0.7.0.jar!/:na]
    at guru.nidi.graphviz.engine.Renderer.toOutputStream(Renderer.java:68) ~[graphviz-java-0.7.0.jar!/:na]
    at org.dddjava.jig.presentation.view.graphvizj.GraphvizjView.lambda$render$0(GraphvizjView.java:30) ~[jig-core-2018.11.2.jar!/:na]
    at org.dddjava.jig.presentation.view.JigDocumentWriter.writeDiagram(JigDocumentWriter.java:37) ~[jig-core-2018.11.2.jar!/:na]
    at org.dddjava.jig.presentation.view.graphvizj.GraphvizjView.render(GraphvizjView.java:26) ~[jig-core-2018.11.2.jar!/:na]
    at org.dddjava.jig.presentation.view.JigModelAndView.render(JigModelAndView.java:16) ~[jig-core-2018.11.2.jar!/:na]
    at org.dddjava.jig.presentation.view.handler.JigDocumentHandlers.handle(JigDocumentHandlers.java:72) ~[jig-core-2018.11.2.jar!/:na]
    at org.dddjava.jig.cli.CommandLineApplication.run(CommandLineApplication.java:52) [classes!/:na]
    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813) [spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
    ... 13 common frames omitted
```

環境依存かと思われる。

# 回避方法

実行環境に Graphviz をインストールしてください。

# 環境確認

- Mac Sierra Java8u111 （該当環境）
- Mac Mojave Java8u181 -> 再現せず
- Debian Java8u111（DockerHub java/8u111-jdk） -> 再現せず

**Comment by irof** [comment]
7605f89d23a04fc3ff25abe106220194b57847ca
