### ISSUE TITLE
ユースケース複合図の出力に失敗する

### ISSUE THREAD

**Issue by kbtaniguchi** [dddjava/jig#472]
## 不具合の内容

```
UseCaseAndFellowsDiagram の出力に失敗しました。
guru.nidi.graphviz.engine.GraphvizException: command '[/bin/sh, -c, dot -Tsvg /var/folders/c3/tzn0h14x2kb5l6m1ydg8lxmc0000gn/T/GraphvizJava/DotEngine2222469709201765357/dotfile.dot -ooutfile.svg]' didn't succeed
	at guru.nidi.graphviz.engine.GraphvizCmdLineEngine.execute(GraphvizCmdLineEngine.java:76)
	at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:211)
	at guru.nidi.graphviz.engine.Renderer.execute(Renderer.java:133)
	at guru.nidi.graphviz.engine.Renderer.toOutputStream(Renderer.java:88)
	at org.dddjava.jig.presentation.view.graphvizj.GraphvizjView.lambda$writeDocument$1(GraphvizjView.java:49)
	at org.dddjava.jig.presentation.view.JigDocumentWriter.write(JigDocumentWriter.java:39)
	at org.dddjava.jig.presentation.view.graphvizj.GraphvizjView.writeDocument(GraphvizjView.java:45)
	at org.dddjava.jig.presentation.view.graphvizj.GraphvizjView.lambda$render$0(GraphvizjView.java:39)
	at java.base/java.util.Collections$SingletonList.forEach(Collections.java:4856)
	at org.dddjava.jig.domain.model.jigdocument.DiagramSources.each(DiagramSources.java:23)
	at org.dddjava.jig.presentation.view.graphvizj.GraphvizjView.render(GraphvizjView.java:39)
	at org.dddjava.jig.presentation.view.JigModelAndView.render(JigModelAndView.java:16)
	at org.dddjava.jig.presentation.view.handler.JigDocumentHandlers.handle(JigDocumentHandlers.java:78)
	at org.dddjava.jig.gradle.JigReportsTask.outputReports(JigReportsTask.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: command '[/bin/sh, -c, dot -Tsvg /var/folders/c3/tzn0h14x2kb5l6m1ydg8lxmc0000gn/T/GraphvizJava/DotEngine2222469709201765357/dotfile.dot -ooutfile.svg]' didn't succeed
	at guru.nidi.graphviz.service.CommandLineExecutor.execute(CommandLineExecutor.java:57)
	at guru.nidi.graphviz.service.CommandRunner.exec(CommandRunner.java:45)
Caused by: java.io.IOException: command '[/bin/sh, -c, dot -Tsvg /var/folders/c3/tzn0h14x2kb5l6m1ydg8lxmc0000gn/T/GraphvizJava/DotEngine2222469709201765357/dotfile.dot -ooutfile.svg]' didn't succeed

	at guru.nidi.graphviz.service.CommandRunner.exec(CommandRunner.java:54)
	at guru.nidi.graphviz.service.CommandRunner.exec(CommandRunner.java:49)
	at guru.nidi.graphviz.engine.GraphvizCmdLineEngine.doExecute(GraphvizCmdLineEngine.java:88)
	at guru.nidi.graphviz.engine.GraphvizCmdLineEngine.execute(GraphvizCmdLineEngine.java:74)
	... 110 more
```

その他のダイアグラム、excelは正常に出力されます。 `use-case-and-fellows.svg` は空ファイルです。

![スクリーンショット 2020-03-30 10 52 24](https://user-images.githubusercontent.com/26402669/77868000-8b79a780-7274-11ea-89d2-89f09f8b6f47.png)

## 環境
- JIGのバージョン: 2020.3.4.1
- 実行方法: GradlePlugin
- Javaのバージョン: AdoptOpenJDK 11.0.4.hs-adpt
- OS: MacOS 10.15.3

**Comment by kbtaniguchi** [comment]
関係あるかどうかわからないですが、jigReportsタスクの実行対象プロジェクトは、gradleのマルチプロジェクト構成で、例えばsharedのような他プロジェクトを参照する構成になっています

**Comment by irof** [comment]
ありがとうございます。
ちょっとわからないですね。サイズの問題なのかその他なのか……。

プロジェクト構成の問題ではなく、出力しているDOTファイルがGraphvizで処理できないのが原因です。
まずい出力があるのか、他の問題があるのか。もしかしたらサイズかもしれない。。。

ログに出力されている `/var/folders/c3/tzn0h14x2kb5l6m1ydg8lxmc0000gn/T/GraphvizJava/DotEngine2222469709201765357/dotfile.dot` をgraphvizで処理してみれば、出力に失敗する原因はわかるかと思います。

**Comment by kbtaniguchi** [comment]
ありがとうございます。
ログに出ていた `dot -Tsvg /var/folders/c3/tzn0h14x2kb5l6m1ydg8lxmc0000gn/T/GraphvizJava/DotEngine2222469709201765357/dotfile.dot -ooutfile.svg` のコマンドをterminalから直接実行すると正常に終了して、ユースケース複合図が得られました。

ファイルサイズは↓の通り、1MBない程度でした。
```
-rw-r--r--  1 k_taniguchi  staff   963K Mar 30 10:36 /var/folders/c3/tzn0h14x2kb5l6m1ydg8lxmc0000gn/T/GraphvizJava/DotEngine2222469709201765357/dotfile.dot
```

**Comment by irof** [comment]
ありがとうございます。
とはいえ大きいですね……（100KB超えると大きいイメージ）

シンタックスエラーなら確実にjigの実装問題なのですが、その系のエラーでもなく（シンタックスエラーならそのエラーメッセージになる）、dotコマンドでは出力できると言うことで、出力時の問題ですね。

graphviz-javaのバージョンアップや設定で改善する可能性もありますが、、、
ちょっとすぐには対応できなさそうです。

**Comment by kbtaniguchi** [comment]
わかりましたー。ありがとうございます。では、このissueは閉じちゃって大丈夫ですかね？

**Comment by irof** [comment]
出力されない不具合なのでこのままでお願いします！

**Comment by irof** [comment]
[2021.1.5](https://github.com/dddjava/jig/releases/tag/2021.1.5) でdotの実行方法変更
[2021.2.1](https://github.com/dddjava/jig/releases/tag/2021.2.1) で出力失敗時に（TEMPでなく）出力先ディレクトリにdotファイルを出すようにしてます。

だめだったら改めて挙げてくださいまし。
