### ISSUE TITLE
verifyJigEnvironmentでOKとなるにもかかわらずjigReportでエラーとなる

### ISSUE THREAD

**Issue by e-yamane** [dddjava/jig#539]
## 不具合の内容
dotコマンドへのパスが相対パスの場合verifyJigEnvironmentでOKとなるにもかかわらずjigReportでcommand not foundになります。
（Graphvizはインストールしてません。独自にdotコマンドを作ってDockerコンテナへの処理移譲を想定してます）

## 環境
- JIGのバージョン: 2020.6.2.1
- 実行方法: GradlePlugin
- Javaのバージョン: openjdk version "11.0.7" 2020-04-14 LTS
- OS: Mac OS Catalina 10.15.5

## 再現手順

```
% ./dot
zsh: no such file or directory: ./dot
% ./gradlew verifyJigEnvironment
(省略)
> [dot] command not found
(省略)
BUILD FAILED
% touch dot
% chmod +x dot
% PATH=$PATH:./
% ./gradlew verifyJigEnvironment
BUILD SUCCESSFUL
% ./gradlew jigReport
(省略)
Caused by: java.io.IOException: /bin/sh: dot: command not found

        at guru.nidi.graphviz.service.CommandLineExecutor.execute(CommandLineExecutor.java:61)
        at guru.nidi.graphviz.service.CommandRunner.exec(CommandRunner.java:70)
        at guru.nidi.graphviz.service.CommandRunner.exec(CommandRunner.java:65)
        at guru.nidi.graphviz.service.CommandRunner.exec(CommandRunner.java:60)
        at guru.nidi.graphviz.engine.GraphvizCmdLineEngine.doExecute(GraphvizCmdLineEngine.java:129)
        at guru.nidi.graphviz.engine.GraphvizCmdLineEngine.execute(GraphvizCmdLineEngine.java:115)
        ... 116 more
```

**Comment by irof** [comment]
2026.4.1以降graphviz使用しなくなったのでcloseします
